version: '3.8'

volumes:
  ghidra-server-repositories:
    name: ghidra-server-repositories

configs:
  ghidra-server-config:
    file: ./server.conf
    name: ghidra-server-config

services:
  nginx:
    build:
      context: nginx
    ports:
      - '13100-13102:13100-13102'
    networks:
      - ghidra-server-external-network
      - ghidra-server-internal-network

  ghidra-server:
    build:
      context: ghidra
      args:
        VERSION: 10.3
        DATE: 20230510
    environment:
      - USERS=${USERS:-admin}
    volumes:
      - ghidra-server-repositories:/repositories
    configs:
      - source: ghidra-server-config
        target: /server.conf
    expose:
      - '13100-13102'
    networks:
      - ghidra-server-internal-network

networks:
  ghidra-server-external-network:
    name: ghidra-server-external-network
    driver_opts:
      encrypted: "true"

  ghidra-server-internal-network:
    name: ghidra-server-internal-network
    driver_opts:
      encrypted: "true"
    internal: true
