version: '3.8'

volumes:
  ghidra-server-repositories:
    name: ghidra-server-repositories

configs:
  ghidra-server-config:
    file: ./server.conf
    name: ghidra-server-config

services:
  ghidra-server:
    build:
      context: .
      args:
        VERSION: 10.3
        DATE: 20230510
    environment:
      - USERS=${USERS:-}
    volumes:
      - ghidra-server-repositories:/repositories
    configs:
      - source: ghidra-server-config
        target: /server.conf
    expose:
      - '13100-13102'
    networks:
      - ghidra-server-network

networks:
  ghidra-server-network:
    name: ghidra-server-network
    driver_opts:
      encrypted: "true"
